"""Add openAItitle column

Revision ID: bdf5f679ab13
Revises: c4cc3164e899
Create Date: 2023-04-16 07:14:32.707323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf5f679ab13'
down_revision = 'c4cc3164e899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openAItitle', sa.String(length=1024), nullable=True))
        batch_op.create_index(batch_op.f('ix_entry_post_openAItitle'), ['openAItitle'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_post_openAItitle'))
        batch_op.drop_column('openAItitle')

    # ### end Alembic commands ###
