"""adding openAIkeyInsights

Revision ID: fa598c2c8d5e
Revises: c3491fade9a7
Create Date: 2024-02-21 18:21:59.548681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa598c2c8d5e'
down_revision = 'c3491fade9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openAIkeyInsights', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_post', schema=None) as batch_op:
        batch_op.drop_column('openAIkeyInsights')

    # ### end Alembic commands ###
